[package]
name = "Compare-Steam-Games"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
reqwest = "0.11"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
