[default]
address = "0.0.0.0"
port = 11235
workers = 4
max_blocking = 512
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
secret_key = "Cl92BeXxMBv4WuXLDzL5JgZlK0J0uBR7KcRml/1JMURhZUKCL0pEHpNTmdr1BiGwwk+4ln8TbsCtS1IDdtApgQ=="

[default.limits]
form = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

# [default.tls]
# certs = "path/to/cert-chain.pem"
# key = "path/to/key.pem"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5

[default.oauth.github]
provider = "GitHub"
client_id = "ad590bff0e92bf8d97f2"
client_secret = "483b0b2e8970be6ccc030b8e8a6f40658632a8fd"
